# Generated by Django 6.0.4 on 2026-05-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('usn', 'semester')},
        ),
    ]
