# Generated by Django 6.0.4 on 2026-05-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('usn', models.CharField()),
                ('sem', models.IntegerField()),
                ('fee', models.BooleanField()),
            ],
            options={
                'unique_together': {('usn', 'sem')},
            },
        ),
    ]
