# Generated by Django 6.0.4 on 2026-05-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('satisfaction', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('recommend', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('comments', models.TextField()),
            ],
        ),
    ]
