# Generated by Django 6.0.4 on 2026-05-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='recommend',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='satisfaction',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='usn',
        ),
    ]
