# Generated by Django 6.0.4 on 2026-05-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('sub_code', models.CharField(max_length=10)),
                ('cie', models.IntegerField()),
            ],
            options={
                'unique_together': {('usn', 'sub_code')},
            },
        ),
    ]
